import { revalidatePath } from 'next/cache'

import { supaFetch } from '@/lib/supabase'
import { verifyAdmin, unauthorizedResponse } from '@/lib/admin-auth'

// ─── Publish quality gate ───
//
// Hard gate that runs before any DB write when action='publish'. Catches the
// failure modes that previously let skeleton/fallback content go live —
// specifically the romance-scammer-red-flags incident where every section
// body was either a meta description ('This section explains...') or just
// the parent-topic taxonomy line ('This topic relates to the broader area
// of...'). The writer prompt forbids these patterns and the buildArticleHtml
// renderer strips them defensively, but neither prevented the row itself
// from being marked status='published' when the AI writers all failed and
// the deterministic fallback fired.
//
// Pure function — no DB calls. Returns { ok, reasons } so the route can
// 422 with a structured payload the admin UI can render.
const SKELETON_OPENER_RE = /^\s*This\s+(?:section|topic|article|guide|page)\s+(?:explains|walks\s+through|defines|addresses|provides|details|covers|describes|outlines|introduces|presents|discusses|examines|explores|breaks\s+down)/i
const TAXONOMY_TRAILER_RE = /This\s+(?:topic|article|guide|page|section)\s+(?:relates\s+to|is\s+part\s+of|falls\s+under|sits\s+under|belongs\s+to)\s+the\s+broader\s+(?:area|topic|category)\s+of/i
const PLACEHOLDER_LINK_VALUES = new Set(['', '#', 'TBD', 'tbd', 'todo', 'TODO'])

function validateForPublish(content) {
  const reasons = []

  // 1. Block deterministic-fallback content. The fallback exists only as a
  //    don't-crash safety net; its output is publish-shaped but topic-agnostic
  //    and grammatically broken (e.g. 'romance scammer red flags scams').
  if (content.ai_model === 'deterministic-fallback') {
    reasons.push("ai_model is 'deterministic-fallback' — content was not generated by an AI writer. Re-run the Generate Article step before publishing.")
  }

  // 2. Inspect each section body for skeleton-content tells.
  const sections = Array.isArray(content.sections) ? content.sections : []
  if (sections.length === 0) {
    reasons.push('content.sections is empty — nothing to publish')
  } else {
    for (let i = 0; i < sections.length; i++) {
      const s = sections[i] || {}
      const heading = String(s.heading || `section ${i + 1}`).slice(0, 80)
      const body = String(s.body || '').trim()

      if (!body) {
        reasons.push(`section "${heading}" has empty body`)
        continue
      }

      const wordCount = body.split(/\s+/).filter(Boolean).length
      if (wordCount < 40) {
        reasons.push(`section "${heading}" body is ${wordCount} words (minimum 40)`)
      }
      if (SKELETON_OPENER_RE.test(body)) {
        reasons.push(`section "${heading}" body opens with a skeleton meta-description ('This section [verb]...') — replace with the actual answer`)
      }
      if (TAXONOMY_TRAILER_RE.test(body)) {
        reasons.push(`section "${heading}" body contains a taxonomy trailer ('This topic relates to the broader area of...') — drop it`)
      }
    }
  }

  // 3. Internal links must point somewhere real.
  const internalLinks = Array.isArray(content.internal_links) ? content.internal_links : []
  for (let i = 0; i < internalLinks.length; i++) {
    const target = String(internalLinks[i]?.target_slug || '').trim()
    if (PLACEHOLDER_LINK_VALUES.has(target)) {
      const anchor = String(internalLinks[i]?.anchor_text || `link ${i + 1}`).slice(0, 60)
      reasons.push(`internal_link "${anchor}" has placeholder target_slug ('${target || '<empty>'}') — drop the entry or supply a real slug`)
    }
  }

  // 4. Author bio must not lead with the author's own name (the renderer
  //    prepends "{name} — " around it and produces 'P. Nair — P. Nair...'
  //    when the model echoes the name back).
  const authorName = String(
    content.ai_audit?.writer_persona?.name || ''
  ).trim()
  const bio = String(content.ai_audit?.author_bio || '').trim()
  if (authorName && bio) {
    const escapedName = authorName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const stutterRe = new RegExp(`^\\s*${escapedName}\\s*[—\\-:,]`, 'i')
    if (stutterRe.test(bio)) {
      reasons.push(`author_bio leads with the author name ('${authorName}') — would render as a stutter`)
    }
  }

  return { ok: reasons.length === 0, reasons }
}

async function syncToLiveBlog({ content, topic }) {
  const replitUrl = process.env.REPLIT_SITE_URL
  const syncSecret = process.env.SYNC_SECRET
  if (!replitUrl || !syncSecret) {
    return { success: false, error: 'REPLIT_SITE_URL and SYNC_SECRET are not configured' }
  }

  const payload = {
    content,
    topic,
    destination: 'blog',
    url: `/blog/${content.slug}`,
  }

  const endpoints = ['/api/sync/blog', '/api/sync/content', '/api/sync/post']

  let lastErr = null
  for (const endpoint of endpoints) {
    try {
      const res = await fetch(`${replitUrl}${endpoint}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${syncSecret}`,
        },
        body: JSON.stringify(payload),
        signal: AbortSignal.timeout(30000),
      })

      if (res.ok) {
        const data = await res.json().catch(() => ({}))
        return { success: true, endpoint, result: data }
      }

      const text = await res.text().catch(() => '')
      lastErr = `${endpoint} -> ${res.status} ${text}`
    } catch (e) {
      lastErr = `${endpoint} -> ${e.message}`
    }
  }

  return { success: false, error: lastErr || 'Unknown sync failure' }
}

/**
 * POST /api/admin/content/[id]/publish
 * Body: { action: "publish" | "unpublish" }
 */
export async function POST(request, { params }) {
  try {
    verifyAdmin(request)

    const { id } = await params
    const { action } = await request.json()
    if (!['publish', 'unpublish'].includes(action)) {
      return Response.json({ error: 'Invalid action. Use publish or unpublish' }, { status: 400 })
    }

    const rows = await supaFetch(`/content?id=eq.${id}&select=*&limit=1`)
    const content = Array.isArray(rows) ? rows[0] : null
    if (!content) return Response.json({ error: 'Content not found' }, { status: 404 })

    // ── Quality gate (publish only) ──
    // Unpublish is always allowed — bad content must always be removable.
    if (action === 'publish') {
      const gate = validateForPublish(content)
      if (!gate.ok) {
        return Response.json({
          error: 'Publish blocked by quality gate',
          reasons: gate.reasons,
          content_id: id,
          slug: content.slug,
          ai_model: content.ai_model,
        }, { status: 422 })
      }
    }

    const nowIso = new Date().toISOString()
    const nowDate = nowIso.slice(0, 10) // YYYY-MM-DD
    const contentUpdates =
      action === 'publish'
        ? { status: 'published', published_at: nowIso, updated_at: nowIso }
        : { status: 'draft', published_at: null, updated_at: nowIso }

    // Update datePublished/dateModified in embedded JSON-LD schema
    if (action === 'publish' && content.full_article) {
      try {
        contentUpdates.full_article = content.full_article.replace(
          /<script type="application\/ld\+json">([\s\S]*?)<\/script>/,
          (match, jsonStr) => {
            try {
              const schema = JSON.parse(jsonStr)
              if (!schema.datePublished || schema.datePublished === schema.dateModified) {
                schema.datePublished = nowDate
              }
              schema.dateModified = nowDate
              return `<script type="application/ld+json">${JSON.stringify(schema)}</script>`
            } catch { return match }
          }
        )
      } catch { /* non-fatal — keep original HTML */ }
    }

    await supaFetch(`/content?id=eq.${id}`, {
      method: 'PATCH',
      headers: { Prefer: 'return=minimal' },
      body: JSON.stringify(contentUpdates),
    })

    if (content.topic_id) {
      const topicStatus = action === 'publish' ? 'published' : 'draft'
      await supaFetch(`/topics?id=eq.${content.topic_id}`, {
        method: 'PATCH',
        headers: { Prefer: 'return=minimal' },
        body: JSON.stringify({ content_status: topicStatus, updated_at: nowIso }),
      })
    }

    let topic = null
    if (content.topic_id) {
      const tRows = await supaFetch(`/topics?id=eq.${content.topic_id}&select=*&limit=1`)
      topic = Array.isArray(tRows) ? tRows[0] : null
    }

    let liveSync = null
    if (action === 'publish') {
      liveSync = await syncToLiveBlog({
        content: { ...content, ...contentUpdates },
        topic,
      })
    } else if (action === 'unpublish') {
      // Notify live site to remove/unpublish the article
      liveSync = await syncToLiveBlog({
        content: { ...content, ...contentUpdates, _action: 'unpublish' },
        topic,
      })
    }

    try {
      revalidatePath('/blog')
      revalidatePath(`/blog/${content.slug}`)
      if (content.topic_id) revalidatePath('/admin/topical-map')
    } catch (e) {
      // non-fatal
      console.error('revalidate failed:', e.message)
    }

    return Response.json({
      success: true,
      id,
      action,
      status: contentUpdates.status,
      published_at: contentUpdates.published_at,
      live_sync: liveSync,
      blog_url: `https://cryptokiller.org/blog/${content.slug}`,
    })
  } catch (error) {
    if (error.message.includes('Unauthorized')) return unauthorizedResponse()
    return Response.json({ error: error.message }, { status: 500 })
  }
}
