import { revalidatePath } from 'next/cache'

import { supaFetch } from '@/lib/supabase'
import { verifyAdmin, unauthorizedResponse } from '@/lib/admin-auth'
import { lintProseFields, collectArticleProseFields, detectHtmlPollution } from '@/lib/content-lint'
import { verifySourceLedger } from '@/lib/source-verify'

// ─── Publish quality gate ───
//
// Hard gate that runs before any DB write when action='publish'. Catches the
// failure modes that previously let skeleton/fallback content go live —
// specifically the romance-scammer-red-flags incident where every section
// body was either a meta description ('This section explains...') or just
// the parent-topic taxonomy line ('This topic relates to the broader area
// of...'). The writer prompt forbids these patterns and the buildArticleHtml
// renderer strips them defensively, but neither prevented the row itself
// from being marked status='published' when the AI writers all failed and
// the deterministic fallback fired.
//
// Pure function — no DB calls. Returns { ok, reasons } so the route can
// 422 with a structured payload the admin UI can render.
const SKELETON_OPENER_RE = /^\s*This\s+(?:section|topic|article|guide|page)\s+(?:explains|walks\s+through|defines|addresses|provides|details|covers|describes|outlines|introduces|presents|discusses|examines|explores|breaks\s+down)/i
const TAXONOMY_TRAILER_RE = /This\s+(?:topic|article|guide|page|section)\s+(?:relates\s+to|is\s+part\s+of|falls\s+under|sits\s+under|belongs\s+to)\s+the\s+broader\s+(?:area|topic|category)\s+of/i
const PLACEHOLDER_LINK_VALUES = new Set(['', '#', 'TBD', 'tbd', 'todo', 'TODO'])

function validateForPublish(content) {
  const reasons = []
  const warnings = []

  // 1. Block deterministic-fallback content. The fallback exists only as a
  //    don't-crash safety net; its output is publish-shaped but topic-agnostic
  //    and grammatically broken (e.g. 'romance scammer red flags scams').
  if (content.ai_model === 'deterministic-fallback') {
    reasons.push("ai_model is 'deterministic-fallback' — content was not generated by an AI writer. Re-run the Generate Article step before publishing.")
  }

  // 2. Inspect each section body for skeleton-content tells.
  const sections = Array.isArray(content.sections) ? content.sections : []
  if (sections.length === 0) {
    reasons.push('content.sections is empty — nothing to publish')
  } else {
    for (let i = 0; i < sections.length; i++) {
      const s = sections[i] || {}
      const heading = String(s.heading || `section ${i + 1}`).slice(0, 80)
      const body = String(s.body || '').trim()

      if (!body) {
        reasons.push(`section "${heading}" has empty body`)
        continue
      }

      const wordCount = body.split(/\s+/).filter(Boolean).length
      if (wordCount < 40) {
        reasons.push(`section "${heading}" body is ${wordCount} words (minimum 40)`)
      }
      if (SKELETON_OPENER_RE.test(body)) {
        reasons.push(`section "${heading}" body opens with a skeleton meta-description ('This section [verb]...') — replace with the actual answer`)
      }
      if (TAXONOMY_TRAILER_RE.test(body)) {
        reasons.push(`section "${heading}" body contains a taxonomy trailer ('This topic relates to the broader area of...') — drop it`)
      }
    }
  }

  // 3. Internal links must point somewhere real.
  const internalLinks = Array.isArray(content.internal_links) ? content.internal_links : []
  for (let i = 0; i < internalLinks.length; i++) {
    const target = String(internalLinks[i]?.target_slug || '').trim()
    if (PLACEHOLDER_LINK_VALUES.has(target)) {
      const anchor = String(internalLinks[i]?.anchor_text || `link ${i + 1}`).slice(0, 60)
      reasons.push(`internal_link "${anchor}" has placeholder target_slug ('${target || '<empty>'}') — drop the entry or supply a real slug`)
    }
  }

  // 4. Author bio must not lead with the author's own name (the renderer
  //    prepends "{name} — " around it and produces 'P. Nair — P. Nair...'
  //    when the model echoes the name back).
  const authorName = String(
    content.ai_audit?.writer_persona?.name || ''
  ).trim()
  const bio = String(content.ai_audit?.author_bio || '').trim()
  if (authorName && bio) {
    const escapedName = authorName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const stutterRe = new RegExp(`^\\s*${escapedName}\\s*[—\\-:,]`, 'i')
    if (stutterRe.test(bio)) {
      reasons.push(`author_bio leads with the author name ('${authorName}') — would render as a stutter`)
    }
  }

  // 5. Deterministic prose lint (lib/content-lint.js): the writer prompt's
  //    anti-slop kill lists, enforced. AI-tell phrases block publish;
  //    slop vocabulary + plural mismatches surface as warnings.
  const lint = lintProseFields(collectArticleProseFields(content))
  reasons.push(...lint.errors)
  warnings.push(...lint.warnings)

  // Structural-pollution gate: full_article must be an HTML fragment, never a
  // full document or a serialized structured-data dump. Blocks render-breaking
  // content from reaching the public renderer. (Audit: YMYL writing-process review.)
  reasons.push(...detectHtmlPollution(content.full_article, 'full_article'))

  // 6. Per-stage deterministic fallbacks (P1-3, content-writing audit
  //    2026-06-11). The overall ai_model check in (1) only catches the
  //    all-stages-failed case. The 4-stage pipeline can fall back per
  //    section/stage — those bodies are outline briefs glued into "prose"
  //    and pass the word-count + opener checks above. The pipeline records
  //    exactly which stages fell back in ai_audit.pipeline_stages; read it.
  //    ALL deterministic-fallback stages → hard block. (YMYL writing-process
  //    review: previously FAQ/aux fallbacks were warn-only, which let a
  //    partly-templated article publish — aux-fallback ships with no schema
  //    enrichment / E-E-A-T fields and FAQ-fallback ships templated outline
  //    hints rather than written answers. The review pipeline already throws
  //    on any stage fallback; the article gate now matches that stance, so
  //    nothing partially-templated reaches a YMYL reader.)
  const stages = Array.isArray(content.ai_audit?.pipeline_stages)
    ? content.ai_audit.pipeline_stages
    : []
  const detStages = stages.filter((s) => s?.label === 'deterministic-fallback')
  const detSections = detStages.filter((s) => String(s?.stage || '').startsWith('section-'))
  const detSkeleton = detStages.filter((s) => s?.stage === 'skeleton')
  const detSoft = detStages.filter((s) => s?.stage === 'faq' || s?.stage === 'aux')
  if (detSections.length > 0) {
    const names = detSections.map((s) => s.heading || s.stage).join(', ')
    reasons.push(`${detSections.length} section(s) used the deterministic fallback (${names}) — the body is an outline brief, not written prose. Re-run Generate Article (or just those sections) before publishing.`)
  }
  if (detSkeleton.length > 0) {
    reasons.push('skeleton stage used the deterministic fallback — title/summary/key-takeaways are templates. Re-run Generate Article before publishing.')
  }
  if (detSoft.length > 0) {
    reasons.push(`${detSoft.map((s) => s.stage).join(' + ')} stage(s) used the deterministic fallback — FAQ/aux fields are templated outline hints, not written content (aux-fallback also ships no schema enrichment). Re-run Generate Article before publishing.`)
  }

  // 7. Quality-auditor verdict gate (lib/review-prompts qualityAuditorPrompt,
  //    run on Claude Sonnet 4.6 at fill time, persisted to ai_audit). The audit
  //    is no longer advisory: a VETO (any_hard_fail) or a clear-fail score
  //    blocks publish. Only enforced when a verdict exists, so legacy rows
  //    without an audit aren't retroactively blocked — re-run Generate Article
  //    to produce a verdict.
  const verdict = content.ai_audit && typeof content.ai_audit === 'object' ? content.ai_audit : null
  if (verdict) {
    if (verdict.hard_fail_checks?.any_hard_fail === true) {
      reasons.push(`quality audit VETO — ${verdict.hard_fail_checks.hard_fail_reason || 'a hard-fail check failed (fabricated source, unverified claim, missing disclosure, fake freshness/reviews, or commodity content)'}. Fix and re-run Generate Article.`)
    }
    const score = Number(verdict.overall_score)
    if (Number.isFinite(score) && score < 60) {
      reasons.push(`quality audit score ${score}/100 is below the YMYL publish floor (60). Address the auditor's critical_fixes and re-run Generate Article.`)
    } else if (Number.isFinite(score) && score < 80) {
      warnings.push(`quality audit score ${score}/100 is below the target (80) — review the auditor's improvements before publishing.`)
    }
  }

  return { ok: reasons.length === 0, reasons, warnings }
}

// ─── Source gate (async — network checks) ───
//
// P0-2 from the content-writing audit (2026-06-11): validateForPublish never
// looked at sources, so dead/hallucinated URLs from a stale outline ledger
// published without re-verification (live catalog shipped ~30 hard-404
// citations, several fabricated, e.g. ic3.gov/Media/Y2026/PreviewYear2026.pdf).
//
// Severity model (conservative — gov sites bot-block datacenter IPs):
//   - HARD-DEAD (404/410, DNS/network failure, malformed, unverifiable
//     domain)                          → error  (blocks publish)
//   - SOFT-FAIL (403/405/5xx/timeouts) → warning (editor judges; these are
//     usually bot blocks on fbi.gov/sec.gov-class hosts, not dead pages)
//   - No current-year source           → error  (the writer prompt's own
//     hard requirement — semantic freshness; was enforced in the legacy
//     generate route but lost in the fill pipeline)
//   - citations count ≠ sources count  → warning (schema drift)
async function validateSourcesForPublish(content) {
  const reasons = []
  const warnings = []
  // Structured list of hard-dead sources, so the admin UI can offer a precise
  // "remove this source & retry" remedy instead of forcing a full (token-
  // expensive) article regeneration over a single bad URL.
  const deadSources = []

  const sources = Array.isArray(content.sources) ? content.sources : []
  if (sources.length === 0) {
    reasons.push('content.sources is empty — a published YMYL article must cite verifiable sources')
    return { ok: false, reasons, warnings, deadSources }
  }

  const HARD_DEAD_RE = /HTTP 404|HTTP 410|malformed URL|unverifiable domain|network:/i
  try {
    const { dropped } = await verifySourceLedger(sources)
    for (const d of dropped) {
      const label = `"${(d.source?.title || d.source?.url || 'source').slice(0, 80)}" (${d.source?.url})`
      if (HARD_DEAD_RE.test(d.reason || '')) {
        reasons.push(`dead source ${label} — ${d.reason}. Replace or remove before publishing.`)
        if (d.source?.url) {
          deadSources.push({
            url: d.source.url,
            title: d.source.title || null,
            reason: d.reason,
          })
        }
      } else {
        warnings.push(`unverified source ${label} — ${d.reason} (likely bot-block; verify in a browser)`)
      }
    }
  } catch (e) {
    // Verification infrastructure failing must not hard-block an editor —
    // but it must be visible.
    warnings.push(`source verification could not run: ${e?.message || e}`)
  }

  const currentYear = String(new Date().getFullYear())
  const hasCurrentYear = sources.some((s) =>
    String(s?.accessed_date || '').startsWith(currentYear) ||
    String(s?.datePublished || '').startsWith(currentYear)
  )
  if (!hasCurrentYear) {
    reasons.push(`no current-year (${currentYear}) source in the ledger — refresh at least one source for semantic freshness (writer-prompt hard requirement)`)
  }

  const citations = Array.isArray(content.citations) ? content.citations : []
  if (citations.length > 0 && citations.length !== sources.length) {
    warnings.push(`citations (${citations.length}) and sources (${sources.length}) counts differ — schema citations may be stale relative to the ledger`)
  }

  return { ok: reasons.length === 0, reasons, warnings, deadSources }
}

async function syncToLiveBlog({ content, topic }) {
  const replitUrl = process.env.REPLIT_SITE_URL
  const syncSecret = process.env.SYNC_SECRET

  // Env-presence diagnostic — boolean only, never leaks secret values. Lets
  // operators tell from the publish response or runtime logs which env var
  // is missing without exposing the secret itself.
  const envState = {
    REPLIT_SITE_URL: replitUrl ? 'set' : 'unset',
    SYNC_SECRET: syncSecret ? 'set' : 'unset',
    REPLIT_SITE_URL_host: replitUrl ? new URL(replitUrl).host : null,
    SYNC_SECRET_length: syncSecret ? syncSecret.length : 0,
  }

  if (!replitUrl || !syncSecret) {
    const result = { success: false, error: 'REPLIT_SITE_URL and SYNC_SECRET are not configured', env: envState }
    console.error('[publish/sync] env missing:', JSON.stringify(envState))
    return result
  }

  const payload = {
    content,
    topic,
    destination: 'blog',
    url: `/blog/${content.slug}`,
  }

  const endpoints = ['/api/sync/blog', '/api/sync/content', '/api/sync/post']
  const attempts = []

  let lastErr = null
  for (const endpoint of endpoints) {
    const startedAt = Date.now()
    try {
      const res = await fetch(`${replitUrl}${endpoint}`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${syncSecret}`,
        },
        body: JSON.stringify(payload),
        signal: AbortSignal.timeout(30000),
      })

      const durationMs = Date.now() - startedAt

      if (res.ok) {
        const data = await res.json().catch(() => ({}))
        attempts.push({ endpoint, status: res.status, durationMs, ok: true })
        console.log('[publish/sync] success:', JSON.stringify({ endpoint, status: res.status, durationMs, slug: content.slug }))
        return { success: true, endpoint, result: data, attempts, env: envState }
      }

      const text = await res.text().catch(() => '')
      const truncated = text.length > 200 ? text.slice(0, 200) + '…' : text
      lastErr = `${endpoint} -> ${res.status} ${truncated}`
      attempts.push({ endpoint, status: res.status, durationMs, ok: false, body: truncated })
    } catch (e) {
      const durationMs = Date.now() - startedAt
      lastErr = `${endpoint} -> ${e.message}`
      attempts.push({ endpoint, status: null, durationMs, ok: false, error: e.message })
    }
  }

  const result = { success: false, error: lastErr || 'Unknown sync failure', attempts, env: envState }
  console.error('[publish/sync] all endpoints failed:', JSON.stringify({
    error: lastErr,
    env: envState,
    attempts,
    slug: content.slug,
  }))
  return result
}

/**
 * POST /api/admin/content/[id]/publish
 * Body: { action: "publish" | "unpublish" }
 */
export async function POST(request, { params }) {
  try {
    verifyAdmin(request)

    const { id } = await params
    const { action } = await request.json()
    if (!['publish', 'unpublish'].includes(action)) {
      return Response.json({ error: 'Invalid action. Use publish or unpublish' }, { status: 400 })
    }

    const rows = await supaFetch(`/content?id=eq.${id}&select=*&limit=1`)
    const content = Array.isArray(rows) ? rows[0] : null
    if (!content) return Response.json({ error: 'Content not found' }, { status: 404 })

    // ── Quality gate (publish only) ──
    // Unpublish is always allowed — bad content must always be removable.
    if (action === 'publish') {
      const gate = validateForPublish(content)
      // Source gate runs even when the prose gate already failed, so the
      // editor sees the full fix list in one 422 instead of fix-retry loops.
      const sourceGate = await validateSourcesForPublish(content)
      const reasons = [...gate.reasons, ...sourceGate.reasons]
      const warnings = [...(gate.warnings || []), ...(sourceGate.warnings || [])]
      if (reasons.length > 0) {
        return Response.json({
          error: 'Publish blocked by quality gate',
          reasons,
          warnings,
          // Machine-actionable: lets the UI offer a one-click remove-and-retry
          // for dead citations rather than a full article regeneration.
          dead_sources: sourceGate.deadSources || [],
          content_id: id,
          slug: content.slug,
          ai_model: content.ai_model,
        }, { status: 422 })
      }
      if (warnings.length > 0) {
        // Non-blocking — log for ops visibility; the admin UI may surface
        // these from the success payload in a later pass.
        console.warn(`[publish] content ${id} gate warnings:`, JSON.stringify(warnings))
      }
    }

    const nowIso = new Date().toISOString()
    const nowDate = nowIso.slice(0, 10) // YYYY-MM-DD
    const contentUpdates =
      action === 'publish'
        ? { status: 'published', published_at: nowIso, updated_at: nowIso }
        : { status: 'draft', published_at: null, updated_at: nowIso }

    // Update datePublished/dateModified in embedded JSON-LD schema
    if (action === 'publish' && content.full_article) {
      try {
        contentUpdates.full_article = content.full_article.replace(
          /<script type="application\/ld\+json">([\s\S]*?)<\/script>/,
          (match, jsonStr) => {
            try {
              const schema = JSON.parse(jsonStr)
              if (!schema.datePublished || schema.datePublished === schema.dateModified) {
                schema.datePublished = nowDate
              }
              schema.dateModified = nowDate
              return `<script type="application/ld+json">${JSON.stringify(schema)}</script>`
            } catch { return match }
          }
        )
      } catch { /* non-fatal — keep original HTML */ }
    }

    await supaFetch(`/content?id=eq.${id}`, {
      method: 'PATCH',
      headers: { Prefer: 'return=minimal' },
      body: JSON.stringify(contentUpdates),
    })

    if (content.topic_id) {
      const topicStatus = action === 'publish' ? 'published' : 'draft'
      await supaFetch(`/topics?id=eq.${content.topic_id}`, {
        method: 'PATCH',
        headers: { Prefer: 'return=minimal' },
        body: JSON.stringify({ content_status: topicStatus, updated_at: nowIso }),
      })
    }

    let topic = null
    if (content.topic_id) {
      const tRows = await supaFetch(`/topics?id=eq.${content.topic_id}&select=*&limit=1`)
      topic = Array.isArray(tRows) ? tRows[0] : null
    }

    let liveSync = null
    if (action === 'publish') {
      liveSync = await syncToLiveBlog({
        content: { ...content, ...contentUpdates },
        topic,
      })
    } else if (action === 'unpublish') {
      // Notify live site to remove/unpublish the article
      liveSync = await syncToLiveBlog({
        content: { ...content, ...contentUpdates, _action: 'unpublish' },
        topic,
      })
    }

    try {
      revalidatePath('/blog')
      revalidatePath(`/blog/${content.slug}`)
      if (content.topic_id) revalidatePath('/admin/topical-map')
    } catch (e) {
      // non-fatal
      console.error('revalidate failed:', e.message)
    }

    return Response.json({
      success: true,
      id,
      action,
      status: contentUpdates.status,
      published_at: contentUpdates.published_at,
      live_sync: liveSync,
      blog_url: `https://cryptokiller.org/blog/${content.slug}`,
    })
  } catch (error) {
    if (error.message.includes('Unauthorized')) return unauthorizedResponse()
    return Response.json({ error: error.message }, { status: 500 })
  }
}
