import { revalidatePath } from 'next/cache'

import { supaFetch } from '@/lib/supabase'
import { verifyAdmin, unauthorizedResponse } from '@/lib/admin-auth'
import { lintProseFields, collectArticleProseFields, detectHtmlPollution } from '@/lib/content-lint'
import { verifySourceLedger } from '@/lib/source-verify'
import { auditFreshness } from '@/lib/audit-freshness'
import { evaluateHardFails } from '@/lib/audit-gate'
import { enqueuePublishOutbox, tryImmediateOutboxDelivery } from '@/lib/publish-outbox'

// ─── Publish quality gate ───
//
// Hard gate that runs before any DB write when action='publish'. Catches the
// failure modes that previously let skeleton/fallback content go live —
// specifically the romance-scammer-red-flags incident where every section
// body was either a meta description ('This section explains...') or just
// the parent-topic taxonomy line ('This topic relates to the broader area
// of...'). The writer prompt forbids these patterns and the buildArticleHtml
// renderer strips them defensively, but neither prevented the row itself
// from being marked status='published' when the AI writers all failed and
// the deterministic fallback fired.
//
// Pure function — no DB calls. Returns { ok, reasons } so the route can
// 422 with a structured payload the admin UI can render.
const SKELETON_OPENER_RE = /^\s*This\s+(?:section|topic|article|guide|page)\s+(?:explains|walks\s+through|defines|addresses|provides|details|covers|describes|outlines|introduces|presents|discusses|examines|explores|breaks\s+down)/i
const TAXONOMY_TRAILER_RE = /This\s+(?:topic|article|guide|page|section)\s+(?:relates\s+to|is\s+part\s+of|falls\s+under|sits\s+under|belongs\s+to)\s+the\s+broader\s+(?:area|topic|category)\s+of/i
const PLACEHOLDER_LINK_VALUES = new Set(['', '#', 'TBD', 'tbd', 'todo', 'TODO'])

function validateForPublish(content) {
  const reasons = []
  const warnings = []

  // 1. Block deterministic-fallback content. The fallback exists only as a
  //    don't-crash safety net; its output is publish-shaped but topic-agnostic
  //    and grammatically broken (e.g. 'romance scammer red flags scams').
  if (content.ai_model === 'deterministic-fallback') {
    reasons.push("ai_model is 'deterministic-fallback' — content was not generated by an AI writer. Re-run the Generate Article step before publishing.")
  }

  // 2. Inspect each section body for skeleton-content tells.
  const sections = Array.isArray(content.sections) ? content.sections : []
  if (sections.length === 0) {
    reasons.push('content.sections is empty — nothing to publish')
  } else {
    for (let i = 0; i < sections.length; i++) {
      const s = sections[i] || {}
      const heading = String(s.heading || `section ${i + 1}`).slice(0, 80)
      const body = String(s.body || '').trim()

      if (!body) {
        reasons.push(`section "${heading}" has empty body`)
        continue
      }

      const wordCount = body.split(/\s+/).filter(Boolean).length
      if (wordCount < 40) {
        reasons.push(`section "${heading}" body is ${wordCount} words (minimum 40)`)
      }
      if (SKELETON_OPENER_RE.test(body)) {
        reasons.push(`section "${heading}" body opens with a skeleton meta-description ('This section [verb]...') — replace with the actual answer`)
      }
      if (TAXONOMY_TRAILER_RE.test(body)) {
        reasons.push(`section "${heading}" body contains a taxonomy trailer ('This topic relates to the broader area of...') — drop it`)
      }
    }
  }

  // 2b. Unrendered visual placeholders (audit 2026-07-05, A1). The fill
  //     pipeline renders [TYPE NEEDED: …] markers into real charts/images;
  //     if that pass failed (or an old row carries the legacy styled
  //     placeholder-box markup), the marker/box survives in full_article.
  //     Publishing a grey placeholder box is never acceptable — block.
  const fullArticleStr = String(content.full_article || '')
  if (/\[\s*(?:CHART|DIAGRAM|IMAGE|SCREENSHOT|PHOTO|INFOGRAPHIC|STEP-BY-STEP)\s*(?:NEEDED)?\s*:/i.test(fullArticleStr)) {
    reasons.push('full_article contains unrendered visual placeholders ([TYPE NEEDED: …]) — re-run Generate Article (the visual pass failed) or remove the markers')
  }
  if (/class="(?:visual-placeholder|placeholder-box)"/i.test(fullArticleStr)) {
    reasons.push('full_article contains legacy placeholder-box markup (grey editor boxes) — re-run Generate Article to render real visuals')
  }

  // 2c. AI disclosure presence (canon Step 6.8 — MANDATORY; audit 2026-07-05
  //     W4c). Warning until the Replit renderer ships the block, then a
  //     blocking reason.
  if (!content.ai_disclosure) {
    warnings.push('ai_disclosure is missing (canon seo-blog-generator Step 6.8) — re-run Generate Article to attach it. Becomes blocking once the live renderer displays the block.')
  }

  // 3. Internal links must point somewhere real.
  const internalLinks = Array.isArray(content.internal_links) ? content.internal_links : []
  for (let i = 0; i < internalLinks.length; i++) {
    const target = String(internalLinks[i]?.target_slug || '').trim()
    if (PLACEHOLDER_LINK_VALUES.has(target)) {
      const anchor = String(internalLinks[i]?.anchor_text || `link ${i + 1}`).slice(0, 60)
      reasons.push(`internal_link "${anchor}" has placeholder target_slug ('${target || '<empty>'}') — drop the entry or supply a real slug`)
    }
  }

  // 4. Author bio must not lead with the author's own name (the renderer
  //    prepends "{name} — " around it and produces 'P. Nair — P. Nair...'
  //    when the model echoes the name back).
  const authorName = String(
    content.ai_audit?.writer_persona?.name || ''
  ).trim()
  const bio = String(content.ai_audit?.author_bio || '').trim()
  if (authorName && bio) {
    const escapedName = authorName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
    const stutterRe = new RegExp(`^\\s*${escapedName}\\s*[—\\-:,]`, 'i')
    if (stutterRe.test(bio)) {
      reasons.push(`author_bio leads with the author name ('${authorName}') — would render as a stutter`)
    }
  }

  // 5. Deterministic prose lint (lib/content-lint.js): the writer prompt's
  //    anti-slop kill lists, enforced. AI-tell phrases block publish;
  //    slop vocabulary + plural mismatches surface as warnings.
  const lint = lintProseFields(collectArticleProseFields(content))
  reasons.push(...lint.errors)
  warnings.push(...lint.warnings)

  // Structural-pollution gate: full_article must be an HTML fragment, never a
  // full document or a serialized structured-data dump. Blocks render-breaking
  // content from reaching the public renderer. (Audit: YMYL writing-process review.)
  reasons.push(...detectHtmlPollution(content.full_article, 'full_article'))

  // 6. Per-stage deterministic fallbacks (P1-3, content-writing audit
  //    2026-06-11). The overall ai_model check in (1) only catches the
  //    all-stages-failed case. The 4-stage pipeline can fall back per
  //    section/stage — those bodies are outline briefs glued into "prose"
  //    and pass the word-count + opener checks above. The pipeline records
  //    exactly which stages fell back in ai_audit.pipeline_stages; read it.
  //    ALL deterministic-fallback stages → hard block. (YMYL writing-process
  //    review: previously FAQ/aux fallbacks were warn-only, which let a
  //    partly-templated article publish — aux-fallback ships with no schema
  //    enrichment / E-E-A-T fields and FAQ-fallback ships templated outline
  //    hints rather than written answers. The review pipeline already throws
  //    on any stage fallback; the article gate now matches that stance, so
  //    nothing partially-templated reaches a YMYL reader.)
  const stages = Array.isArray(content.ai_audit?.pipeline_stages)
    ? content.ai_audit.pipeline_stages
    : []
  const detStages = stages.filter((s) => s?.label === 'deterministic-fallback')
  const detSections = detStages.filter((s) => String(s?.stage || '').startsWith('section-'))
  const detSkeleton = detStages.filter((s) => s?.stage === 'skeleton')
  const detSoft = detStages.filter((s) => s?.stage === 'faq' || s?.stage === 'aux')
  if (detSections.length > 0) {
    const names = detSections.map((s) => s.heading || s.stage).join(', ')
    reasons.push(`${detSections.length} section(s) used the deterministic fallback (${names}) — the body is an outline brief, not written prose. Re-run Generate Article (or just those sections) before publishing.`)
  }
  if (detSkeleton.length > 0) {
    reasons.push('skeleton stage used the deterministic fallback — title/summary/key-takeaways are templates. Re-run Generate Article before publishing.')
  }
  if (detSoft.length > 0) {
    reasons.push(`${detSoft.map((s) => s.stage).join(' + ')} stage(s) used the deterministic fallback — FAQ/aux fields are templated outline hints, not written content (aux-fallback also ships no schema enrichment). Re-run Generate Article before publishing.`)
  }

  // 7. Quality-auditor verdict gate (lib/review-prompts qualityAuditorPrompt,
  //    run on Claude Sonnet 4.6 at fill time, persisted to ai_audit). The audit
  //    is no longer advisory: a failed hard-fail check or a clear-fail score
  //    blocks publish. Only enforced when a verdict exists, so legacy rows
  //    without an audit aren't retroactively blocked — re-run Generate Article
  //    to produce a verdict.
  //
  //    Two things stand between the verdict and a block. `auditFreshness` asks
  //    whether the verdict is still about this draft. `evaluateHardFails` asks
  //    which checks actually failed, rather than trusting the model's own
  //    `any_hard_fail` summary — which fires on checks that do not apply to the
  //    content type. Both exist so the editor is never stuck choosing between an
  //    unfixable veto and an override that disables every other check.
  // Surfaced in the 422 so the editor UI can say "re-audit" rather than
  // "rewrite", and so the remediation endpoint knows a re-audit alone may clear
  // the block.
  let auditStale = false
  let auditUnverifiable = false

  const verdict = content.ai_audit && typeof content.ai_audit === 'object' ? content.ai_audit : null
  if (verdict) {
    const score = Number(verdict.overall_score)
    // An auditor that we KNOW errored must not sail through as a pass. `fill`
    // (and the Re-run Audit route) now stamp audit_status:'failed' when the
    // auditor throws — that explicit marker is what we block on. This is a
    // recoverable block: "Re-run Audit" (re-runs just the auditor, cheap) or
    // "Publish anyway" to override.
    //
    // We deliberately do NOT block on a merely-absent verdict (no
    // overall_score, no hard_fail_checks): verified against the live DB, ALL
    // existing content rows are in that state (the content auditor has never
    // persisted a verdict — see the separate diagnosis), so blocking on
    // absence would retroactively trap every published article on republish.
    // Legacy rows therefore keep their current pass-through behavior; only a
    // fresh, explicitly-failed audit blocks.
    if (verdict.audit_status === 'failed') {
      reasons.push(
        'quality audit did not complete — no verdict on record' +
        (verdict.audit_error ? ` (${verdict.audit_error})` : '') +
        '. Click "Re-run Audit" to re-run just the auditor, or use "Publish anyway" to override. A failed audit is not a passing audit.'
      )
    } else {
      // Is this verdict still about the article as it stands? A verdict stamped
      // with a content_hash that no longer matches describes text the editor has
      // since replaced. Repeating its findings traps the editor: they fix every
      // cited problem and the same dead reasons come back, leaving the override
      // as the only exit. So a stale verdict blocks on its staleness, not on its
      // (now unfounded) contents.
      const freshness = auditFreshness(content)

      if (freshness.state === 'stale') {
        reasons.push(
          'the quality audit is stale — the article changed after the audit ran, so its findings describe text that is no longer here' +
          (freshness.audited_at ? ` (audited ${freshness.audited_at})` : '') +
          '. Click "Re-run Audit" to get a verdict on the current draft.'
        )
        auditStale = true
      } else {
        // 'fresh' and 'unverifiable' are both enforced. Unverifiable means the
        // verdict predates hash stamping: it cannot be proven current, but
        // waving it through would let every legacy row bypass the gate.
        const hardFails = evaluateHardFails(verdict, content)
        for (const f of hardFails.failed) {
          reasons.push(`quality audit VETO (${f.key}) — ${f.reason}`)
        }
        // Checks the auditor could not answer, and vetoes attributable to a
        // check that does not apply to this content type, surface as warnings
        // instead of silently vanishing.
        warnings.push(...hardFails.warnings)
        if (hardFails.failed.length > 0 && freshness.state === 'unverifiable') {
          auditUnverifiable = true
        }
      }

      if (Number.isFinite(score) && score < 60) {
        reasons.push(`quality audit score ${score}/100 is below the YMYL publish floor (60). Address the auditor's critical_fixes and re-run Generate Article.`)
      } else if (Number.isFinite(score) && score < 80) {
        warnings.push(`quality audit score ${score}/100 is below the target (80) — review the auditor's improvements before publishing.`)
      }
    }
  }

  return { ok: reasons.length === 0, reasons, warnings, auditStale, auditUnverifiable }
}

// ─── Source gate (async — network checks) ───
//
// P0-2 from the content-writing audit (2026-06-11): validateForPublish never
// looked at sources, so dead/hallucinated URLs from a stale outline ledger
// published without re-verification (live catalog shipped ~30 hard-404
// citations, several fabricated, e.g. ic3.gov/Media/Y2026/PreviewYear2026.pdf).
//
// Severity model (conservative — gov sites bot-block datacenter IPs):
//   - HARD-DEAD (404/410, DNS/network failure, malformed, unverifiable
//     domain)                          → error  (blocks publish)
//   - SOFT-FAIL (403/405/5xx/timeouts) → warning (editor judges; these are
//     usually bot blocks on fbi.gov/sec.gov-class hosts, not dead pages)
//   - No current-year source           → error  (the writer prompt's own
//     hard requirement — semantic freshness; was enforced in the legacy
//     generate route but lost in the fill pipeline)
//   - citations count ≠ sources count  → warning (schema drift)
async function validateSourcesForPublish(content) {
  const reasons = []
  const warnings = []
  // Structured list of hard-dead sources, so the admin UI can offer a precise
  // "remove this source & retry" remedy instead of forcing a full (token-
  // expensive) article regeneration over a single bad URL.
  const deadSources = []

  const sources = Array.isArray(content.sources) ? content.sources : []
  if (sources.length === 0) {
    reasons.push('content.sources is empty — a published YMYL article must cite verifiable sources')
    return { ok: false, reasons, warnings, deadSources }
  }

  // Audit 2026-07-05 (A8): 'network-transient:' (timeouts/resets on slow gov
  // hosts) is deliberately EXCLUDED — those soft-warn instead of blocking.
  // Note `network:` below uses a negative lookahead so it doesn't match the
  // transient prefix.
  const HARD_DEAD_RE = /HTTP 404|HTTP 410|malformed URL|unverifiable domain|network(?!-transient):/i
  try {
    const { dropped } = await verifySourceLedger(sources)
    for (const d of dropped) {
      const label = `"${(d.source?.title || d.source?.url || 'source').slice(0, 80)}" (${d.source?.url})`
      if (HARD_DEAD_RE.test(d.reason || '')) {
        reasons.push(`dead source ${label} — ${d.reason}. Replace or remove before publishing.`)
        if (d.source?.url) {
          deadSources.push({
            url: d.source.url,
            title: d.source.title || null,
            reason: d.reason,
          })
        }
      } else {
        warnings.push(`unverified source ${label} — ${d.reason} (likely bot-block; verify in a browser)`)
      }
    }
  } catch (e) {
    // Verification infrastructure failing must not hard-block an editor —
    // but it must be visible.
    warnings.push(`source verification could not run: ${e?.message || e}`)
  }

  const currentYear = String(new Date().getFullYear())
  const hasCurrentYear = sources.some((s) =>
    String(s?.accessed_date || '').startsWith(currentYear) ||
    String(s?.datePublished || '').startsWith(currentYear)
  )
  if (!hasCurrentYear) {
    reasons.push(`no current-year (${currentYear}) source in the ledger — refresh at least one source for semantic freshness (writer-prompt hard requirement)`)
  }

  const citations = Array.isArray(content.citations) ? content.citations : []
  if (citations.length > 0 && citations.length !== sources.length) {
    warnings.push(`citations (${citations.length}) and sources (${sources.length}) counts differ — schema citations may be stale relative to the ledger`)
  }

  return { ok: reasons.length === 0, reasons, warnings, deadSources }
}

/**
 * POST /api/admin/content/[id]/publish
 * Body: { action: "publish" | "unpublish" }
 */
export async function POST(request, { params }) {
  try {
    verifyAdmin(request)

    const { id } = await params
    const { action, override } = await request.json()
    if (!['publish', 'unpublish'].includes(action)) {
      return Response.json({ error: 'Invalid action. Use publish or unpublish' }, { status: 400 })
    }
    // Operator escape hatch: an explicit override lets a solo editor ship past
    // the quality gate rather than dead-ending on a flaky auditor or a source
    // check they've manually verified. It is deliberately loud — the bypassed
    // reasons are recorded on the row (ai_audit.published_override) for a
    // permanent audit trail — and never silent.
    const overrideGate = action === 'publish' && override === true
    let overrideRecord = null

    const rows = await supaFetch(`/content?id=eq.${id}&select=*&limit=1`)
    const content = Array.isArray(rows) ? rows[0] : null
    if (!content) return Response.json({ error: 'Content not found' }, { status: 404 })

    // ── Quality gate (publish only) ──
    // Unpublish is always allowed — bad content must always be removable.
    if (action === 'publish') {
      const gate = validateForPublish(content)
      // Source gate runs even when the prose gate already failed, so the
      // editor sees the full fix list in one 422 instead of fix-retry loops.
      const sourceGate = await validateSourcesForPublish(content)
      const reasons = [...gate.reasons, ...sourceGate.reasons]
      const warnings = [...(gate.warnings || []), ...(sourceGate.warnings || [])]
      if (reasons.length > 0 && !overrideGate) {
        return Response.json({
          error: 'Publish blocked by quality gate',
          reasons,
          warnings,
          // Every gate block is overridable — the operator is never trapped.
          // The UI re-POSTs { action:'publish', override:true } after showing
          // these reasons.
          overridable: true,
          // Machine-actionable: lets the UI offer a one-click remove-and-retry
          // for dead citations rather than a full article regeneration.
          dead_sources: sourceGate.deadSources || [],
          // The audit's findings are about an older draft — a re-audit, not an
          // edit, is the fix. Distinguished from `audit_unverifiable`, where the
          // findings are being enforced but cannot be proven current.
          audit_stale: gate.auditStale === true,
          audit_unverifiable: gate.auditUnverifiable === true,
          content_id: id,
          slug: content.slug,
          ai_model: content.ai_model,
        }, { status: 422 })
      }
      if (reasons.length > 0 && overrideGate) {
        // Bypassing the gate — record exactly what was skipped, by whom-context
        // and when, onto the row's ai_audit for a durable trail.
        console.warn(`[publish] content ${id} published via OVERRIDE, bypassing:`, JSON.stringify(reasons))
        overrideRecord = {
          at: new Date().toISOString(),
          bypassed_reasons: reasons,
          bypassed_warnings: warnings,
        }
      }
      if (warnings.length > 0) {
        // Non-blocking — log for ops visibility; the admin UI may surface
        // these from the success payload in a later pass.
        console.warn(`[publish] content ${id} gate warnings:`, JSON.stringify(warnings))
      }
    }

    const nowIso = new Date().toISOString()
    const nowDate = nowIso.slice(0, 10) // YYYY-MM-DD
    const contentUpdates =
      action === 'publish'
        ? { status: 'published', published_at: nowIso, updated_at: nowIso }
        : { status: 'draft', published_at: null, updated_at: nowIso }

    // Persist the override trail onto the row so a bypassed publish is always
    // reconstructable (what was skipped, when) — never a silent flip.
    if (overrideRecord) {
      const baseAudit = content.ai_audit && typeof content.ai_audit === 'object' ? content.ai_audit : {}
      contentUpdates.ai_audit = { ...baseAudit, published_override: overrideRecord }
    }

    // Update datePublished/dateModified in embedded JSON-LD schema
    if (action === 'publish' && content.full_article) {
      try {
        contentUpdates.full_article = content.full_article.replace(
          /<script type="application\/ld\+json">([\s\S]*?)<\/script>/,
          (match, jsonStr) => {
            try {
              const schema = JSON.parse(jsonStr)
              if (!schema.datePublished || schema.datePublished === schema.dateModified) {
                schema.datePublished = nowDate
              }
              schema.dateModified = nowDate
              return `<script type="application/ld+json">${JSON.stringify(schema)}</script>`
            } catch { return match }
          }
        )
      } catch { /* non-fatal — keep original HTML */ }
    }

    await supaFetch(`/content?id=eq.${id}`, {
      method: 'PATCH',
      headers: { Prefer: 'return=minimal' },
      body: JSON.stringify(contentUpdates),
    })

    if (content.topic_id) {
      const topicStatus = action === 'publish' ? 'published' : 'draft'
      await supaFetch(`/topics?id=eq.${content.topic_id}`, {
        method: 'PATCH',
        headers: { Prefer: 'return=minimal' },
        body: JSON.stringify({ content_status: topicStatus, updated_at: nowIso }),
      })
    }

    let topic = null
    if (content.topic_id) {
      const tRows = await supaFetch(`/topics?id=eq.${content.topic_id}&select=*&limit=1`)
      topic = Array.isArray(tRows) ? tRows[0] : null
    }

    // Durable outbox + best-effort immediate delivery. DB flip already
    // succeeded; Replit sync retries via /api/cron/publish-outbox.
    let liveSync = null
    let outboxJob = null
    try {
      outboxJob = await enqueuePublishOutbox({
        kind: 'content',
        entityId: id,
        slug: content.slug,
        action,
      })
      liveSync = await tryImmediateOutboxDelivery(outboxJob)
    } catch (outboxErr) {
      console.error('[publish] outbox enqueue/delivery failed:', outboxErr.message)
      liveSync = { success: false, error: outboxErr.message }
    }

    try {
      revalidatePath('/blog')
      revalidatePath(`/blog/${content.slug}`)
      if (content.topic_id) revalidatePath('/admin/topical-map')
    } catch (e) {
      // non-fatal
      console.error('revalidate failed:', e.message)
    }

    // The DB flip succeeded (success:true), but that is NOT the same as the
    // live site receiving the article. Outbox retries when immediate sync
    // fails; surface sync_pending so the UI can show "syncing in background".
    const syncOk = liveSync?.success === true
    const syncPending = !syncOk && !!outboxJob?.id
    return Response.json({
      success: true,
      id,
      action,
      status: contentUpdates.status,
      published_at: contentUpdates.published_at,
      overridden: !!overrideRecord,
      override: overrideRecord,
      sync_ok: syncOk,
      sync_pending: syncPending,
      sync_error: syncOk
        ? null
        : (liveSync?.error || liveSync?.message || 'live-site sync pending — worker will retry'),
      outbox_id: outboxJob?.id || null,
      live_sync: liveSync,
      blog_url: `https://cryptokiller.org/blog/${content.slug}`,
      topic_title: topic?.title || null,
    })
  } catch (error) {
    if (error.message.includes('Unauthorized')) return unauthorizedResponse()
    return Response.json({ error: error.message }, { status: 500 })
  }
}
